# Generated by Django 2.1.7 on 2019-03-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user',
            new_name='username',
        ),
    ]
