# Generated by Django 2.1.7 on 2019-03-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0002_auto_20190301_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='username',
            new_name='user',
        ),
    ]
