# Generated by Django 2.1.7 on 2019-03-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0003_auto_20190301_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
    ]
