# Generated by Django 2.1.7 on 2019-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0005_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(max_length=100),
        ),
    ]
