# Generated by Django 2.1.7 on 2019-03-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0006_auto_20190301_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
