# Generated by Django 2.1.7 on 2019-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0009_charactermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='job',
            field=models.CharField(choices=[('Knight', 'Knight'), ('Mage', 'Mage'), ('Rogue', 'Rogue'), ('Healer', 'Healer')], default='green', max_length=6),
        ),
    ]
