# Generated by Django 2.1.7 on 2019-03-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0010_auto_20190302_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='job',
            field=models.CharField(choices=[('Knight', 'Knight'), ('Mage', 'Mage'), ('Rogue', 'Rogue'), ('Healer', 'Healer')], default='Knight', max_length=6),
        ),
    ]
