# Generated by Django 2.1.7 on 2019-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0011_auto_20190302_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='accE1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='accE2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='armorE',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='magA',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='magD',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='mainE',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='mp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='offE',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='physA',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='physD',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
