# Generated by Django 2.1.7 on 2019-03-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0013_accessory_armour_weapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100, null=True)),
                ('hp', models.IntegerField(default=1)),
                ('mp', models.IntegerField(default=1)),
                ('physA', models.IntegerField(default=1)),
                ('physD', models.IntegerField(default=1)),
                ('magA', models.IntegerField(default=1)),
                ('magD', models.IntegerField(default=1)),
                ('mainE', models.CharField(max_length=150, null=True)),
                ('offE', models.CharField(max_length=150, null=True)),
                ('armorE', models.CharField(max_length=150, null=True)),
                ('accE1', models.CharField(max_length=150, null=True)),
                ('accE2', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
