# Generated by Django 2.1.7 on 2019-03-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0014_basecharacters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('minLevel', models.IntegerField(default=1, null=True)),
                ('bonusType1', models.CharField(max_length=100, null=True)),
                ('bonus1', models.IntegerField(default=1, null=True)),
                ('bonusType2', models.CharField(max_length=100, null=True)),
                ('bonus2', models.IntegerField(default=1, null=True)),
                ('bonusType3', models.CharField(max_length=100, null=True)),
                ('bonus3', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmourList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('minLevel', models.IntegerField(default=1, null=True)),
                ('pdBonus', models.IntegerField(default=1, null=True)),
                ('mdBonus', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('minLevel', models.IntegerField(default=1, null=True)),
                ('paBonus', models.IntegerField(default=1, null=True)),
                ('maBonus', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Armour',
            new_name='OffHandList',
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Weapons',
        ),
        migrations.AlterField(
            model_name='basecharacters',
            name='armorE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.ArmourList'),
        ),
        migrations.AlterField(
            model_name='basecharacters',
            name='mainE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.WeaponList'),
        ),
    ]
