# Generated by Django 2.1.7 on 2019-03-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0015_auto_20190302_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='baseCharacters',
            new_name='BaseCharacterList',
        ),
    ]
