# Generated by Django 2.1.7 on 2019-03-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0016_auto_20190302_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecharacterlist',
            old_name='job',
            new_name='job_name',
        ),
        migrations.RemoveField(
            model_name='basecharacterlist',
            name='accE2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='accE2',
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='minLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armourlist',
            name='mdBonus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armourlist',
            name='minLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armourlist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armourlist',
            name='pdBonus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basecharacterlist',
            name='accE1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.AccessoryList'),
        ),
        migrations.AlterField(
            model_name='basecharacterlist',
            name='offE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.OffHandList'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.BaseCharacterList'),
        ),
        migrations.AlterField(
            model_name='offhandlist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponlist',
            name='maBonus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weaponlist',
            name='minLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weaponlist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponlist',
            name='paBonus',
            field=models.IntegerField(default=1),
        ),
    ]
