# Generated by Django 2.1.7 on 2019-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0017_auto_20190302_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorylist',
            name='bonus1',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='bonus2',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='bonus3',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='bonusType1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='bonusType2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accessorylist',
            name='bonusType3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
