# Generated by Django 2.1.7 on 2019-03-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0018_auto_20190302_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='accE1',
            new_name='accE',
        ),
        migrations.RemoveField(
            model_name='basecharacterlist',
            name='accE1',
        ),
        migrations.AddField(
            model_name='basecharacterlist',
            name='accE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.AccessoryList'),
        ),
        migrations.AlterField(
            model_name='basecharacterlist',
            name='armorE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.ArmourList'),
        ),
        migrations.AlterField(
            model_name='basecharacterlist',
            name='mainE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.WeaponList'),
        ),
        migrations.AlterField(
            model_name='basecharacterlist',
            name='offE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.OffHandList'),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='job',
            field=models.CharField(choices=[('Knight', 'Knight'), ('Mage', 'Mage')], default='Knight', max_length=6),
        ),
    ]
