# Generated by Django 2.1.7 on 2019-03-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0019_auto_20190302_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='accE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.AccessoryList'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armorE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.ArmourList'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mainE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.WeaponList'),
        ),
        migrations.AlterField(
            model_name='character',
            name='offE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterinfo.OffHandList'),
        ),
    ]
