# Generated by Django 2.1.7 on 2019-03-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0021_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='map',
            new_name='mapseed',
        ),
    ]
