# Generated by Django 2.1.7 on 2019-03-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0022_auto_20190302_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='posy',
            field=models.IntegerField(default=16),
        ),
    ]
