# Generated by Django 2.1.7 on 2019-03-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0024_auto_20190302_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='user',
            new_name='character',
        ),
    ]
