# Generated by Django 2.1.7 on 2019-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterinfo', '0025_auto_20190302_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='timestamp',
            field=models.IntegerField(default=1),
        ),
    ]
